/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Cocoa/Cocoa.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"

#import "EDAMLimits.h"

enum EDAMPrivilegeLevel {
  PrivilegeLevel_NORMAL = 1,
  PrivilegeLevel_PREMIUM = 3,
  PrivilegeLevel_VIP = 7,
  PrivilegeLevel_ADMIN = 9
};

enum EDAMQueryFormat {
  QueryFormat_USER = 1,
  QueryFormat_SEXP = 2
};

enum EDAMNoteSortOrder {
  NoteSortOrder_CREATED = 1,
  NoteSortOrder_UPDATED = 2,
  NoteSortOrder_RELEVANCE = 3,
  NoteSortOrder_UPDATE_SEQUENCE_NUMBER = 4
};

enum EDAMPremiumOrderStatus {
  PremiumOrderStatus_NONE = 0,
  PremiumOrderStatus_PENDING = 1,
  PremiumOrderStatus_ACTIVE = 2,
  PremiumOrderStatus_FAILED = 3,
  PremiumOrderStatus_CANCELLATION_PENDING = 4,
  PremiumOrderStatus_CANCELED = 5
};

typedef int32_t EDAMUserID;

typedef NSString * EDAMGuid;

typedef int64_t EDAMTimestamp;

@interface EDAMData : NSObject {
  NSData * __bodyHash;
  int32_t __size;
  NSData * __body;

  BOOL __bodyHash_isset;
  BOOL __size_isset;
  BOOL __body_isset;
}

- (id) initWithBodyHash: (NSData *) bodyHash size: (int32_t) size body: (NSData *) body;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSData *) bodyHash;
- (void) setBodyHash: (NSData *) bodyHash;
- (BOOL) bodyHashIsSet;

- (int32_t) size;
- (void) setSize: (int32_t) size;
- (BOOL) sizeIsSet;

- (NSData *) body;
- (void) setBody: (NSData *) body;
- (BOOL) bodyIsSet;

@end

@interface EDAMUserAttributes : NSObject {
  NSString * __defaultLocationName;
  double __defaultLatitude;
  double __defaultLongitude;
  BOOL __preactivation;
  NSArray * __viewedPromotions;
  NSString * __incomingEmailAddress;
  NSArray * __recentMailedAddresses;
  NSString * __comments;
  EDAMTimestamp __dateAgreedToTermsOfService;
  int32_t __maxReferrals;
  int32_t __referralCount;
  NSString * __refererCode;
  EDAMTimestamp __sentEmailDate;
  int32_t __sentEmailCount;
  int32_t __dailyEmailLimit;
  EDAMTimestamp __emailOptOutDate;
  EDAMTimestamp __partnerEmailOptInDate;
  NSString * __preferredLanguage;
  NSString * __preferredCountry;

  BOOL __defaultLocationName_isset;
  BOOL __defaultLatitude_isset;
  BOOL __defaultLongitude_isset;
  BOOL __preactivation_isset;
  BOOL __viewedPromotions_isset;
  BOOL __incomingEmailAddress_isset;
  BOOL __recentMailedAddresses_isset;
  BOOL __comments_isset;
  BOOL __dateAgreedToTermsOfService_isset;
  BOOL __maxReferrals_isset;
  BOOL __referralCount_isset;
  BOOL __refererCode_isset;
  BOOL __sentEmailDate_isset;
  BOOL __sentEmailCount_isset;
  BOOL __dailyEmailLimit_isset;
  BOOL __emailOptOutDate_isset;
  BOOL __partnerEmailOptInDate_isset;
  BOOL __preferredLanguage_isset;
  BOOL __preferredCountry_isset;
}

- (id) initWithDefaultLocationName: (NSString *) defaultLocationName defaultLatitude: (double) defaultLatitude defaultLongitude: (double) defaultLongitude preactivation: (BOOL) preactivation viewedPromotions: (NSArray *) viewedPromotions incomingEmailAddress: (NSString *) incomingEmailAddress recentMailedAddresses: (NSArray *) recentMailedAddresses comments: (NSString *) comments dateAgreedToTermsOfService: (EDAMTimestamp) dateAgreedToTermsOfService maxReferrals: (int32_t) maxReferrals referralCount: (int32_t) referralCount refererCode: (NSString *) refererCode sentEmailDate: (EDAMTimestamp) sentEmailDate sentEmailCount: (int32_t) sentEmailCount dailyEmailLimit: (int32_t) dailyEmailLimit emailOptOutDate: (EDAMTimestamp) emailOptOutDate partnerEmailOptInDate: (EDAMTimestamp) partnerEmailOptInDate preferredLanguage: (NSString *) preferredLanguage preferredCountry: (NSString *) preferredCountry;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSString *) defaultLocationName;
- (void) setDefaultLocationName: (NSString *) defaultLocationName;
- (BOOL) defaultLocationNameIsSet;

- (double) defaultLatitude;
- (void) setDefaultLatitude: (double) defaultLatitude;
- (BOOL) defaultLatitudeIsSet;

- (double) defaultLongitude;
- (void) setDefaultLongitude: (double) defaultLongitude;
- (BOOL) defaultLongitudeIsSet;

- (BOOL) preactivation;
- (void) setPreactivation: (BOOL) preactivation;
- (BOOL) preactivationIsSet;

- (NSArray *) viewedPromotions;
- (void) setViewedPromotions: (NSArray *) viewedPromotions;
- (BOOL) viewedPromotionsIsSet;

- (NSString *) incomingEmailAddress;
- (void) setIncomingEmailAddress: (NSString *) incomingEmailAddress;
- (BOOL) incomingEmailAddressIsSet;

- (NSArray *) recentMailedAddresses;
- (void) setRecentMailedAddresses: (NSArray *) recentMailedAddresses;
- (BOOL) recentMailedAddressesIsSet;

- (NSString *) comments;
- (void) setComments: (NSString *) comments;
- (BOOL) commentsIsSet;

- (EDAMTimestamp) dateAgreedToTermsOfService;
- (void) setDateAgreedToTermsOfService: (EDAMTimestamp) dateAgreedToTermsOfService;
- (BOOL) dateAgreedToTermsOfServiceIsSet;

- (int32_t) maxReferrals;
- (void) setMaxReferrals: (int32_t) maxReferrals;
- (BOOL) maxReferralsIsSet;

- (int32_t) referralCount;
- (void) setReferralCount: (int32_t) referralCount;
- (BOOL) referralCountIsSet;

- (NSString *) refererCode;
- (void) setRefererCode: (NSString *) refererCode;
- (BOOL) refererCodeIsSet;

- (EDAMTimestamp) sentEmailDate;
- (void) setSentEmailDate: (EDAMTimestamp) sentEmailDate;
- (BOOL) sentEmailDateIsSet;

- (int32_t) sentEmailCount;
- (void) setSentEmailCount: (int32_t) sentEmailCount;
- (BOOL) sentEmailCountIsSet;

- (int32_t) dailyEmailLimit;
- (void) setDailyEmailLimit: (int32_t) dailyEmailLimit;
- (BOOL) dailyEmailLimitIsSet;

- (EDAMTimestamp) emailOptOutDate;
- (void) setEmailOptOutDate: (EDAMTimestamp) emailOptOutDate;
- (BOOL) emailOptOutDateIsSet;

- (EDAMTimestamp) partnerEmailOptInDate;
- (void) setPartnerEmailOptInDate: (EDAMTimestamp) partnerEmailOptInDate;
- (BOOL) partnerEmailOptInDateIsSet;

- (NSString *) preferredLanguage;
- (void) setPreferredLanguage: (NSString *) preferredLanguage;
- (BOOL) preferredLanguageIsSet;

- (NSString *) preferredCountry;
- (void) setPreferredCountry: (NSString *) preferredCountry;
- (BOOL) preferredCountryIsSet;

@end

@interface EDAMAccounting : NSObject {
  int64_t __uploadLimit;
  EDAMTimestamp __uploadLimitEnd;
  int64_t __uploadLimitNextMonth;
  int __premiumServiceStatus;
  NSString * __premiumOrderNumber;
  NSString * __premiumCommerceService;
  EDAMTimestamp __premiumServiceStart;
  NSString * __premiumServiceSKU;
  EDAMTimestamp __lastSuccessfulCharge;
  EDAMTimestamp __lastFailedCharge;
  NSString * __lastFailedChargeReason;
  EDAMTimestamp __nextPaymentDue;
  EDAMTimestamp __premiumLockUntil;
  EDAMTimestamp __updated;
  NSString * __premiumSubscriptionNumber;

  BOOL __uploadLimit_isset;
  BOOL __uploadLimitEnd_isset;
  BOOL __uploadLimitNextMonth_isset;
  BOOL __premiumServiceStatus_isset;
  BOOL __premiumOrderNumber_isset;
  BOOL __premiumCommerceService_isset;
  BOOL __premiumServiceStart_isset;
  BOOL __premiumServiceSKU_isset;
  BOOL __lastSuccessfulCharge_isset;
  BOOL __lastFailedCharge_isset;
  BOOL __lastFailedChargeReason_isset;
  BOOL __nextPaymentDue_isset;
  BOOL __premiumLockUntil_isset;
  BOOL __updated_isset;
  BOOL __premiumSubscriptionNumber_isset;
}

- (id) initWithUploadLimit: (int64_t) uploadLimit uploadLimitEnd: (EDAMTimestamp) uploadLimitEnd uploadLimitNextMonth: (int64_t) uploadLimitNextMonth premiumServiceStatus: (int) premiumServiceStatus premiumOrderNumber: (NSString *) premiumOrderNumber premiumCommerceService: (NSString *) premiumCommerceService premiumServiceStart: (EDAMTimestamp) premiumServiceStart premiumServiceSKU: (NSString *) premiumServiceSKU lastSuccessfulCharge: (EDAMTimestamp) lastSuccessfulCharge lastFailedCharge: (EDAMTimestamp) lastFailedCharge lastFailedChargeReason: (NSString *) lastFailedChargeReason nextPaymentDue: (EDAMTimestamp) nextPaymentDue premiumLockUntil: (EDAMTimestamp) premiumLockUntil updated: (EDAMTimestamp) updated premiumSubscriptionNumber: (NSString *) premiumSubscriptionNumber;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (int64_t) uploadLimit;
- (void) setUploadLimit: (int64_t) uploadLimit;
- (BOOL) uploadLimitIsSet;

- (EDAMTimestamp) uploadLimitEnd;
- (void) setUploadLimitEnd: (EDAMTimestamp) uploadLimitEnd;
- (BOOL) uploadLimitEndIsSet;

- (int64_t) uploadLimitNextMonth;
- (void) setUploadLimitNextMonth: (int64_t) uploadLimitNextMonth;
- (BOOL) uploadLimitNextMonthIsSet;

- (int) premiumServiceStatus;
- (void) setPremiumServiceStatus: (int) premiumServiceStatus;
- (BOOL) premiumServiceStatusIsSet;

- (NSString *) premiumOrderNumber;
- (void) setPremiumOrderNumber: (NSString *) premiumOrderNumber;
- (BOOL) premiumOrderNumberIsSet;

- (NSString *) premiumCommerceService;
- (void) setPremiumCommerceService: (NSString *) premiumCommerceService;
- (BOOL) premiumCommerceServiceIsSet;

- (EDAMTimestamp) premiumServiceStart;
- (void) setPremiumServiceStart: (EDAMTimestamp) premiumServiceStart;
- (BOOL) premiumServiceStartIsSet;

- (NSString *) premiumServiceSKU;
- (void) setPremiumServiceSKU: (NSString *) premiumServiceSKU;
- (BOOL) premiumServiceSKUIsSet;

- (EDAMTimestamp) lastSuccessfulCharge;
- (void) setLastSuccessfulCharge: (EDAMTimestamp) lastSuccessfulCharge;
- (BOOL) lastSuccessfulChargeIsSet;

- (EDAMTimestamp) lastFailedCharge;
- (void) setLastFailedCharge: (EDAMTimestamp) lastFailedCharge;
- (BOOL) lastFailedChargeIsSet;

- (NSString *) lastFailedChargeReason;
- (void) setLastFailedChargeReason: (NSString *) lastFailedChargeReason;
- (BOOL) lastFailedChargeReasonIsSet;

- (EDAMTimestamp) nextPaymentDue;
- (void) setNextPaymentDue: (EDAMTimestamp) nextPaymentDue;
- (BOOL) nextPaymentDueIsSet;

- (EDAMTimestamp) premiumLockUntil;
- (void) setPremiumLockUntil: (EDAMTimestamp) premiumLockUntil;
- (BOOL) premiumLockUntilIsSet;

- (EDAMTimestamp) updated;
- (void) setUpdated: (EDAMTimestamp) updated;
- (BOOL) updatedIsSet;

- (NSString *) premiumSubscriptionNumber;
- (void) setPremiumSubscriptionNumber: (NSString *) premiumSubscriptionNumber;
- (BOOL) premiumSubscriptionNumberIsSet;

@end

@interface EDAMUser : NSObject {
  EDAMUserID __id;
  NSString * __username;
  NSString * __email;
  NSString * __name;
  NSString * __timezone;
  int __privilege;
  EDAMTimestamp __created;
  EDAMTimestamp __updated;
  EDAMTimestamp __deleted;
  BOOL __active;
  NSString * __shardId;
  EDAMUserAttributes * __attributes;
  EDAMAccounting * __accounting;

  BOOL __id_isset;
  BOOL __username_isset;
  BOOL __email_isset;
  BOOL __name_isset;
  BOOL __timezone_isset;
  BOOL __privilege_isset;
  BOOL __created_isset;
  BOOL __updated_isset;
  BOOL __deleted_isset;
  BOOL __active_isset;
  BOOL __shardId_isset;
  BOOL __attributes_isset;
  BOOL __accounting_isset;
}

- (id) initWithId: (EDAMUserID) id username: (NSString *) username email: (NSString *) email name: (NSString *) name timezone: (NSString *) timezone privilege: (int) privilege created: (EDAMTimestamp) created updated: (EDAMTimestamp) updated deleted: (EDAMTimestamp) deleted active: (BOOL) active shardId: (NSString *) shardId attributes: (EDAMUserAttributes *) attributes accounting: (EDAMAccounting *) accounting;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (EDAMUserID) id;
- (void) setId: (EDAMUserID) id;
- (BOOL) idIsSet;

- (NSString *) username;
- (void) setUsername: (NSString *) username;
- (BOOL) usernameIsSet;

- (NSString *) email;
- (void) setEmail: (NSString *) email;
- (BOOL) emailIsSet;

- (NSString *) name;
- (void) setName: (NSString *) name;
- (BOOL) nameIsSet;

- (NSString *) timezone;
- (void) setTimezone: (NSString *) timezone;
- (BOOL) timezoneIsSet;

- (int) privilege;
- (void) setPrivilege: (int) privilege;
- (BOOL) privilegeIsSet;

- (EDAMTimestamp) created;
- (void) setCreated: (EDAMTimestamp) created;
- (BOOL) createdIsSet;

- (EDAMTimestamp) updated;
- (void) setUpdated: (EDAMTimestamp) updated;
- (BOOL) updatedIsSet;

- (EDAMTimestamp) deleted;
- (void) setDeleted: (EDAMTimestamp) deleted;
- (BOOL) deletedIsSet;

- (BOOL) active;
- (void) setActive: (BOOL) active;
- (BOOL) activeIsSet;

- (NSString *) shardId;
- (void) setShardId: (NSString *) shardId;
- (BOOL) shardIdIsSet;

- (EDAMUserAttributes *) attributes;
- (void) setAttributes: (EDAMUserAttributes *) attributes;
- (BOOL) attributesIsSet;

- (EDAMAccounting *) accounting;
- (void) setAccounting: (EDAMAccounting *) accounting;
- (BOOL) accountingIsSet;

@end

@interface EDAMTag : NSObject {
  EDAMGuid __guid;
  NSString * __name;
  EDAMGuid __parentGuid;
  int32_t __updateSequenceNum;

  BOOL __guid_isset;
  BOOL __name_isset;
  BOOL __parentGuid_isset;
  BOOL __updateSequenceNum_isset;
}

- (id) initWithGuid: (EDAMGuid) guid name: (NSString *) name parentGuid: (EDAMGuid) parentGuid updateSequenceNum: (int32_t) updateSequenceNum;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (EDAMGuid) guid;
- (void) setGuid: (EDAMGuid) guid;
- (BOOL) guidIsSet;

- (NSString *) name;
- (void) setName: (NSString *) name;
- (BOOL) nameIsSet;

- (EDAMGuid) parentGuid;
- (void) setParentGuid: (EDAMGuid) parentGuid;
- (BOOL) parentGuidIsSet;

- (int32_t) updateSequenceNum;
- (void) setUpdateSequenceNum: (int32_t) updateSequenceNum;
- (BOOL) updateSequenceNumIsSet;

@end

@interface EDAMResourceAttributes : NSObject {
  NSString * __sourceURL;
  EDAMTimestamp __timestamp;
  double __latitude;
  double __longitude;
  double __altitude;
  NSString * __cameraMake;
  NSString * __cameraModel;
  BOOL __clientWillIndex;
  NSString * __recoType;
  NSString * __fileName;
  BOOL __attachment;

  BOOL __sourceURL_isset;
  BOOL __timestamp_isset;
  BOOL __latitude_isset;
  BOOL __longitude_isset;
  BOOL __altitude_isset;
  BOOL __cameraMake_isset;
  BOOL __cameraModel_isset;
  BOOL __clientWillIndex_isset;
  BOOL __recoType_isset;
  BOOL __fileName_isset;
  BOOL __attachment_isset;
}

- (id) initWithSourceURL: (NSString *) sourceURL timestamp: (EDAMTimestamp) timestamp latitude: (double) latitude longitude: (double) longitude altitude: (double) altitude cameraMake: (NSString *) cameraMake cameraModel: (NSString *) cameraModel clientWillIndex: (BOOL) clientWillIndex recoType: (NSString *) recoType fileName: (NSString *) fileName attachment: (BOOL) attachment;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSString *) sourceURL;
- (void) setSourceURL: (NSString *) sourceURL;
- (BOOL) sourceURLIsSet;

- (EDAMTimestamp) timestamp;
- (void) setTimestamp: (EDAMTimestamp) timestamp;
- (BOOL) timestampIsSet;

- (double) latitude;
- (void) setLatitude: (double) latitude;
- (BOOL) latitudeIsSet;

- (double) longitude;
- (void) setLongitude: (double) longitude;
- (BOOL) longitudeIsSet;

- (double) altitude;
- (void) setAltitude: (double) altitude;
- (BOOL) altitudeIsSet;

- (NSString *) cameraMake;
- (void) setCameraMake: (NSString *) cameraMake;
- (BOOL) cameraMakeIsSet;

- (NSString *) cameraModel;
- (void) setCameraModel: (NSString *) cameraModel;
- (BOOL) cameraModelIsSet;

- (BOOL) clientWillIndex;
- (void) setClientWillIndex: (BOOL) clientWillIndex;
- (BOOL) clientWillIndexIsSet;

- (NSString *) recoType;
- (void) setRecoType: (NSString *) recoType;
- (BOOL) recoTypeIsSet;

- (NSString *) fileName;
- (void) setFileName: (NSString *) fileName;
- (BOOL) fileNameIsSet;

- (BOOL) attachment;
- (void) setAttachment: (BOOL) attachment;
- (BOOL) attachmentIsSet;

@end

@interface EDAMResource : NSObject {
  EDAMGuid __guid;
  EDAMGuid __noteGuid;
  EDAMData * __data;
  NSString * __mime;
  int16_t __width;
  int16_t __height;
  int16_t __duration;
  BOOL __active;
  EDAMData * __recognition;
  EDAMResourceAttributes * __attributes;
  int32_t __updateSequenceNum;

  BOOL __guid_isset;
  BOOL __noteGuid_isset;
  BOOL __data_isset;
  BOOL __mime_isset;
  BOOL __width_isset;
  BOOL __height_isset;
  BOOL __duration_isset;
  BOOL __active_isset;
  BOOL __recognition_isset;
  BOOL __attributes_isset;
  BOOL __updateSequenceNum_isset;
}

- (id) initWithGuid: (EDAMGuid) guid noteGuid: (EDAMGuid) noteGuid data: (EDAMData *) data mime: (NSString *) mime width: (int16_t) width height: (int16_t) height duration: (int16_t) duration active: (BOOL) active recognition: (EDAMData *) recognition attributes: (EDAMResourceAttributes *) attributes updateSequenceNum: (int32_t) updateSequenceNum;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (EDAMGuid) guid;
- (void) setGuid: (EDAMGuid) guid;
- (BOOL) guidIsSet;

- (EDAMGuid) noteGuid;
- (void) setNoteGuid: (EDAMGuid) noteGuid;
- (BOOL) noteGuidIsSet;

- (EDAMData *) data;
- (void) setData: (EDAMData *) data;
- (BOOL) dataIsSet;

- (NSString *) mime;
- (void) setMime: (NSString *) mime;
- (BOOL) mimeIsSet;

- (int16_t) width;
- (void) setWidth: (int16_t) width;
- (BOOL) widthIsSet;

- (int16_t) height;
- (void) setHeight: (int16_t) height;
- (BOOL) heightIsSet;

- (int16_t) duration;
- (void) setDuration: (int16_t) duration;
- (BOOL) durationIsSet;

- (BOOL) active;
- (void) setActive: (BOOL) active;
- (BOOL) activeIsSet;

- (EDAMData *) recognition;
- (void) setRecognition: (EDAMData *) recognition;
- (BOOL) recognitionIsSet;

- (EDAMResourceAttributes *) attributes;
- (void) setAttributes: (EDAMResourceAttributes *) attributes;
- (BOOL) attributesIsSet;

- (int32_t) updateSequenceNum;
- (void) setUpdateSequenceNum: (int32_t) updateSequenceNum;
- (BOOL) updateSequenceNumIsSet;

@end

@interface EDAMNoteAttributes : NSObject {
  EDAMTimestamp __subjectDate;
  double __latitude;
  double __longitude;
  double __altitude;
  NSString * __author;
  NSString * __source;
  NSString * __sourceURL;
  NSString * __sourceApplication;

  BOOL __subjectDate_isset;
  BOOL __latitude_isset;
  BOOL __longitude_isset;
  BOOL __altitude_isset;
  BOOL __author_isset;
  BOOL __source_isset;
  BOOL __sourceURL_isset;
  BOOL __sourceApplication_isset;
}

- (id) initWithSubjectDate: (EDAMTimestamp) subjectDate latitude: (double) latitude longitude: (double) longitude altitude: (double) altitude author: (NSString *) author source: (NSString *) source sourceURL: (NSString *) sourceURL sourceApplication: (NSString *) sourceApplication;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (EDAMTimestamp) subjectDate;
- (void) setSubjectDate: (EDAMTimestamp) subjectDate;
- (BOOL) subjectDateIsSet;

- (double) latitude;
- (void) setLatitude: (double) latitude;
- (BOOL) latitudeIsSet;

- (double) longitude;
- (void) setLongitude: (double) longitude;
- (BOOL) longitudeIsSet;

- (double) altitude;
- (void) setAltitude: (double) altitude;
- (BOOL) altitudeIsSet;

- (NSString *) author;
- (void) setAuthor: (NSString *) author;
- (BOOL) authorIsSet;

- (NSString *) source;
- (void) setSource: (NSString *) source;
- (BOOL) sourceIsSet;

- (NSString *) sourceURL;
- (void) setSourceURL: (NSString *) sourceURL;
- (BOOL) sourceURLIsSet;

- (NSString *) sourceApplication;
- (void) setSourceApplication: (NSString *) sourceApplication;
- (BOOL) sourceApplicationIsSet;

@end

@interface EDAMNote : NSObject {
  EDAMGuid __guid;
  NSString * __title;
  NSString * __content;
  NSData * __contentHash;
  int32_t __contentLength;
  EDAMTimestamp __created;
  EDAMTimestamp __updated;
  EDAMTimestamp __deleted;
  BOOL __active;
  int32_t __updateSequenceNum;
  NSString * __notebookGuid;
  NSArray * __tagGuids;
  NSArray * __resources;
  EDAMNoteAttributes * __attributes;

  BOOL __guid_isset;
  BOOL __title_isset;
  BOOL __content_isset;
  BOOL __contentHash_isset;
  BOOL __contentLength_isset;
  BOOL __created_isset;
  BOOL __updated_isset;
  BOOL __deleted_isset;
  BOOL __active_isset;
  BOOL __updateSequenceNum_isset;
  BOOL __notebookGuid_isset;
  BOOL __tagGuids_isset;
  BOOL __resources_isset;
  BOOL __attributes_isset;
}

- (id) initWithGuid: (EDAMGuid) guid title: (NSString *) title content: (NSString *) content contentHash: (NSData *) contentHash contentLength: (int32_t) contentLength created: (EDAMTimestamp) created updated: (EDAMTimestamp) updated deleted: (EDAMTimestamp) deleted active: (BOOL) active updateSequenceNum: (int32_t) updateSequenceNum notebookGuid: (NSString *) notebookGuid tagGuids: (NSArray *) tagGuids resources: (NSArray *) resources attributes: (EDAMNoteAttributes *) attributes;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (EDAMGuid) guid;
- (void) setGuid: (EDAMGuid) guid;
- (BOOL) guidIsSet;

- (NSString *) title;
- (void) setTitle: (NSString *) title;
- (BOOL) titleIsSet;

- (NSString *) content;
- (void) setContent: (NSString *) content;
- (BOOL) contentIsSet;

- (NSData *) contentHash;
- (void) setContentHash: (NSData *) contentHash;
- (BOOL) contentHashIsSet;

- (int32_t) contentLength;
- (void) setContentLength: (int32_t) contentLength;
- (BOOL) contentLengthIsSet;

- (EDAMTimestamp) created;
- (void) setCreated: (EDAMTimestamp) created;
- (BOOL) createdIsSet;

- (EDAMTimestamp) updated;
- (void) setUpdated: (EDAMTimestamp) updated;
- (BOOL) updatedIsSet;

- (EDAMTimestamp) deleted;
- (void) setDeleted: (EDAMTimestamp) deleted;
- (BOOL) deletedIsSet;

- (BOOL) active;
- (void) setActive: (BOOL) active;
- (BOOL) activeIsSet;

- (int32_t) updateSequenceNum;
- (void) setUpdateSequenceNum: (int32_t) updateSequenceNum;
- (BOOL) updateSequenceNumIsSet;

- (NSString *) notebookGuid;
- (void) setNotebookGuid: (NSString *) notebookGuid;
- (BOOL) notebookGuidIsSet;

- (NSArray *) tagGuids;
- (void) setTagGuids: (NSArray *) tagGuids;
- (BOOL) tagGuidsIsSet;

- (NSArray *) resources;
- (void) setResources: (NSArray *) resources;
- (BOOL) resourcesIsSet;

- (EDAMNoteAttributes *) attributes;
- (void) setAttributes: (EDAMNoteAttributes *) attributes;
- (BOOL) attributesIsSet;

@end

@interface EDAMPublishing : NSObject {
  NSString * __uri;
  int __order;
  BOOL __ascending;
  NSString * __publicDescription;

  BOOL __uri_isset;
  BOOL __order_isset;
  BOOL __ascending_isset;
  BOOL __publicDescription_isset;
}

- (id) initWithUri: (NSString *) uri order: (int) order ascending: (BOOL) ascending publicDescription: (NSString *) publicDescription;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSString *) uri;
- (void) setUri: (NSString *) uri;
- (BOOL) uriIsSet;

- (int) order;
- (void) setOrder: (int) order;
- (BOOL) orderIsSet;

- (BOOL) ascending;
- (void) setAscending: (BOOL) ascending;
- (BOOL) ascendingIsSet;

- (NSString *) publicDescription;
- (void) setPublicDescription: (NSString *) publicDescription;
- (BOOL) publicDescriptionIsSet;

@end

@interface EDAMNotebook : NSObject {
  EDAMGuid __guid;
  NSString * __name;
  int32_t __updateSequenceNum;
  BOOL __defaultNotebook;
  EDAMTimestamp __serviceCreated;
  EDAMTimestamp __serviceUpdated;
  EDAMPublishing * __publishing;
  BOOL __published;

  BOOL __guid_isset;
  BOOL __name_isset;
  BOOL __updateSequenceNum_isset;
  BOOL __defaultNotebook_isset;
  BOOL __serviceCreated_isset;
  BOOL __serviceUpdated_isset;
  BOOL __publishing_isset;
  BOOL __published_isset;
}

- (id) initWithGuid: (EDAMGuid) guid name: (NSString *) name updateSequenceNum: (int32_t) updateSequenceNum defaultNotebook: (BOOL) defaultNotebook serviceCreated: (EDAMTimestamp) serviceCreated serviceUpdated: (EDAMTimestamp) serviceUpdated publishing: (EDAMPublishing *) publishing published: (BOOL) published;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (EDAMGuid) guid;
- (void) setGuid: (EDAMGuid) guid;
- (BOOL) guidIsSet;

- (NSString *) name;
- (void) setName: (NSString *) name;
- (BOOL) nameIsSet;

- (int32_t) updateSequenceNum;
- (void) setUpdateSequenceNum: (int32_t) updateSequenceNum;
- (BOOL) updateSequenceNumIsSet;

- (BOOL) defaultNotebook;
- (void) setDefaultNotebook: (BOOL) defaultNotebook;
- (BOOL) defaultNotebookIsSet;

- (EDAMTimestamp) serviceCreated;
- (void) setServiceCreated: (EDAMTimestamp) serviceCreated;
- (BOOL) serviceCreatedIsSet;

- (EDAMTimestamp) serviceUpdated;
- (void) setServiceUpdated: (EDAMTimestamp) serviceUpdated;
- (BOOL) serviceUpdatedIsSet;

- (EDAMPublishing *) publishing;
- (void) setPublishing: (EDAMPublishing *) publishing;
- (BOOL) publishingIsSet;

- (BOOL) published;
- (void) setPublished: (BOOL) published;
- (BOOL) publishedIsSet;

@end

@interface EDAMSavedSearch : NSObject {
  EDAMGuid __guid;
  NSString * __name;
  NSString * __query;
  int __format;
  int32_t __updateSequenceNum;

  BOOL __guid_isset;
  BOOL __name_isset;
  BOOL __query_isset;
  BOOL __format_isset;
  BOOL __updateSequenceNum_isset;
}

- (id) initWithGuid: (EDAMGuid) guid name: (NSString *) name query: (NSString *) query format: (int) format updateSequenceNum: (int32_t) updateSequenceNum;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (EDAMGuid) guid;
- (void) setGuid: (EDAMGuid) guid;
- (BOOL) guidIsSet;

- (NSString *) name;
- (void) setName: (NSString *) name;
- (BOOL) nameIsSet;

- (NSString *) query;
- (void) setQuery: (NSString *) query;
- (BOOL) queryIsSet;

- (int) format;
- (void) setFormat: (int) format;
- (BOOL) formatIsSet;

- (int32_t) updateSequenceNum;
- (void) setUpdateSequenceNum: (int32_t) updateSequenceNum;
- (BOOL) updateSequenceNumIsSet;

@end

@interface EDAMTypesConstants {
}
+ (NSString *) EDAM_NOTE_SOURCE_WEB_CLIP;
+ (NSString *) EDAM_NOTE_SOURCE_MAIL_CLIP;
+ (NSString *) EDAM_NOTE_SOURCE_MAIL_SMTP_GATEWAY;
@end
